CREATE DATABASE IF NOT EXISTS TR_UTIL;
ALTER DATABASE TR_UTIL DEFAULT CHARACTER SET 'utf8' DEFAULT COLLATE 'utf8_general_ci';

USE TR_UTIL;

DROP FUNCTION IF EXISTS OBJ_NEW;

DELIMITER //

CREATE FUNCTION OBJ_NEW()
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE rv MEDIUMBLOB DEFAULT NULL;
  SET rv = CONCAT('o', ':');
  SET rv = CONCAT(LENGTH(rv), ':', rv);
  RETURN rv;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS OBJ_UNSET;

DELIMITER //

CREATE FUNCTION OBJ_UNSET(obj MEDIUMBLOB, tag TEXT)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  RETURN __OBJ_SET_RAW(obj, tag, NULL);
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS OBJ_SET_INT;

DELIMITER //

CREATE FUNCTION OBJ_SET_INT(obj MEDIUMBLOB, tag TEXT, num BIGINT)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE v MEDIUMBLOB DEFAULT NULL;
  SET v = __OBJ_ENCODE_INTEGER(num);
  IF v IS NULL THEN
    RETURN NULL;
  END IF;
  RETURN __OBJ_SET_RAW(obj, tag, v);
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS OBJ_GET_INT;

DELIMITER //

CREATE FUNCTION OBJ_GET_INT(obj MEDIUMBLOB, tag TEXT)
RETURNS BIGINT
DETERMINISTIC NO SQL
BEGIN
  DECLARE v MEDIUMBLOB DEFAULT NULL;
  SET v = __OBJ_GET_RAW(obj, tag);
  IF v IS NULL THEN
    RETURN NULL;
  END IF;
  RETURN __OBJ_DECODE_INTEGER(v);
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS OBJ_SET_FLOAT;

DELIMITER //

CREATE FUNCTION OBJ_SET_FLOAT(obj MEDIUMBLOB, tag TEXT, num DOUBLE)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE v MEDIUMBLOB DEFAULT NULL;
  SET v = __OBJ_ENCODE_FLOAT(num);
  IF v IS NULL THEN
    RETURN NULL;
  END IF;
  RETURN __OBJ_SET_RAW(obj, tag, v);  
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS OBJ_GET_FLOAT;

DELIMITER //

CREATE FUNCTION OBJ_GET_FLOAT(obj MEDIUMBLOB, tag TEXT)
RETURNS DOUBLE
DETERMINISTIC NO SQL
BEGIN
  DECLARE v MEDIUMBLOB DEFAULT NULL;
  SET v = __OBJ_GET_RAW(obj, tag);
  IF v IS NULL THEN
    RETURN NULL;
  END IF;
  RETURN __OBJ_DECODE_FLOAT(v);
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS OBJ_SET_STR;

DELIMITER //

CREATE FUNCTION OBJ_SET_STR(obj MEDIUMBLOB, tag TEXT, str MEDIUMBLOB)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE v MEDIUMBLOB DEFAULT NULL;
  SET v = __OBJ_ENCODE_STRING(str);
  IF v IS NULL THEN
    RETURN NULL;
  END IF;
  RETURN __OBJ_SET_RAW(obj, tag, v);
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS OBJ_GET_STR;

DELIMITER //

CREATE FUNCTION OBJ_GET_STR(obj MEDIUMBLOB, tag TEXT)
RETURNS BIGINT
DETERMINISTIC NO SQL
BEGIN
  DECLARE v MEDIUMBLOB DEFAULT NULL;
  SET v = __OBJ_GET_RAW(obj, tag);
  IF v IS NULL THEN
    RETURN NULL;
  END IF;
  RETURN __OBJ_DECODE_STRING(v);
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_FIRST_ITEM_LENGTH;

DELIMITER //

CREATE FUNCTION __OBJ_FIRST_ITEM_LENGTH(obj MEDIUMBLOB)
RETURNS BIGINT
DETERMINISTIC NO SQL
BEGIN
  DECLARE a INTEGER DEFAULT NULL;
  DECLARE len BIGINT DEFAULT NULL;
  SET a = LOCATE(':', obj);
  IF a < 2 THEN
    RETURN NULL;
  END IF;
  SET len = SUBSTRING(obj, 1, a - 1);
  IF a + len = LENGTH(obj) THEN
    RETURN a + len;
  ELSEIF (a + len < LENGTH(obj)) AND (SUBSTRING(obj, a + len + 1, 1) = ':') THEN
    RETURN a + len + 1;
  END IF;
  RETURN NULL;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_FIRST_ITEM_PAYLOAD;

DELIMITER //

CREATE FUNCTION __OBJ_FIRST_ITEM_PAYLOAD(obj MEDIUMBLOB)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE a INTEGER DEFAULT NULL;
  DECLARE len BIGINT DEFAULT NULL;
  SET a = LOCATE(':', obj);
  IF a < 2 THEN
    RETURN NULL;
  END IF;
  SET len = SUBSTRING(obj, 1, a - 1);
  IF (a + len = LENGTH(obj)) OR ((a + len < LENGTH(obj)) AND (SUBSTRING(obj, a + len + 1, 1) = ':')) THEN
    RETURN SUBSTRING(obj, a + 1, len);
  END IF;
  RETURN NULL;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_ITEM_PAYLOAD_TYPE;

DELIMITER //

CREATE FUNCTION __OBJ_ITEM_PAYLOAD_TYPE(obj MEDIUMBLOB)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE a INTEGER DEFAULT NULL;
  DECLARE len BIGINT DEFAULT NULL;
  DECLARE type MEDIUMBLOB DEFAULT NULL;
  SET a = LOCATE(':', obj);
  IF a < 2 THEN
    RETURN NULL;
  END IF;
  RETURN SUBSTRING(obj, 1, a - 1);
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_ITEM_PAYLOAD_RAW;

DELIMITER //

CREATE FUNCTION __OBJ_ITEM_PAYLOAD_RAW(obj MEDIUMBLOB)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE a INTEGER DEFAULT NULL;
  DECLARE len BIGINT DEFAULT NULL;
  SET a = LOCATE(':', obj);
  IF a < 2 THEN
    RETURN NULL;
  END IF;
  RETURN SUBSTRING(obj, a + 1);
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_ENCODE_INTEGER;

DELIMITER //

CREATE FUNCTION __OBJ_ENCODE_INTEGER(num BIGINT)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE rv MEDIUMBLOB DEFAULT NULL;
  SET rv = num;
  SET rv = CONCAT('i', ':', rv);
  SET rv = CONCAT(LENGTH(rv), ':', rv);
  RETURN rv;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_DECODE_INTEGER;

DELIMITER //

CREATE FUNCTION __OBJ_DECODE_INTEGER(obj MEDIUMBLOB)
RETURNS BIGINT
DETERMINISTIC NO SQL
BEGIN
  DECLARE pl MEDIUMBLOB DEFAULT NULL;
  DECLARE tp MEDIUMBLOB DEFAULT NULL;
  DECLARE rw MEDIUMBLOB DEFAULT NULL;
  DECLARE rv BIGINT DEFAULT NULL;
  SET pl = __OBJ_FIRST_ITEM_PAYLOAD(obj);
  IF pl IS NULL THEN
    RETURN NULL;
  END IF;
  SET tp = __OBJ_ITEM_PAYLOAD_TYPE(pl);
  IF tp IS NULL OR tp <> 'i' THEN
    RETURN NULL;
  END IF;
  SET rw = __OBJ_ITEM_PAYLOAD_RAW(pl);
  IF rw IS NULL THEN
    RETURN NULL;
  END IF;
  SET rv = 0 + rw;
  RETURN rv;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_FLOAT_FORMAT;

DELIMITER //

CREATE FUNCTION __OBJ_FLOAT_FORMAT(n DOUBLE)
RETURNS TEXT
DETERMINISTIC NO SQL
BEGIN
  DECLARE rv TEXT DEFAULT NULL;
  DECLARE sign TEXT DEFAULT NULL;
  DECLARE sig DOUBLE DEFAULT NULL;
  DECLARE exp INTEGER DEFAULT NULL;
  IF n < 0.0 THEN
    SET sign = '-';
    SET n = -n;
  ELSEIF n > 0.0 THEN
    SET sign = '';
  ELSE
   RETURN '0.0';
  END IF;  
  SET exp = FLOOR(LOG10(n));
  SET sig = n / POW(10, exp);
  SET rv = CONCAT(sign, CAST(ROUND(sig, 19) AS BINARY));
  IF exp <> 0 THEN
    SET rv = CONCAT(rv, 'e', exp);
  END IF;
  RETURN rv;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_ENCODE_FLOAT;

DELIMITER //

CREATE FUNCTION __OBJ_ENCODE_FLOAT(num DOUBLE)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE rv MEDIUMBLOB DEFAULT NULL;
  SET rv = CONCAT('f', ':', __OBJ_FLOAT_FORMAT(num));
  SET rv = CONCAT(LENGTH(rv), ':', rv);
  RETURN rv;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_DECODE_FLOAT;

DELIMITER //

CREATE FUNCTION __OBJ_DECODE_FLOAT(obj MEDIUMBLOB)
RETURNS DOUBLE
DETERMINISTIC NO SQL
BEGIN
  DECLARE pl MEDIUMBLOB DEFAULT NULL;
  DECLARE tp MEDIUMBLOB DEFAULT NULL;
  DECLARE rw MEDIUMBLOB DEFAULT NULL;
  DECLARE rv DOUBLE DEFAULT NULL;
  SET pl = __OBJ_FIRST_ITEM_PAYLOAD(obj);
  IF pl IS NULL THEN
    RETURN NULL;
  END IF;
  SET tp = __OBJ_ITEM_PAYLOAD_TYPE(pl);
  IF tp IS NULL OR (tp <> 'f' AND tp <> 'i') THEN
    RETURN NULL;
  END IF;
  SET rw = __OBJ_ITEM_PAYLOAD_RAW(pl);
  IF rw IS NULL THEN
    RETURN NULL;
  END IF;
  SET rv = 0.0 + rw;
  RETURN rv;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_ENCODE_STRING;

DELIMITER //

CREATE FUNCTION __OBJ_ENCODE_STRING(str MEDIUMBLOB)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE rv MEDIUMBLOB DEFAULT NULL;
  SET rv = CONCAT('s', ':', str);
  SET rv = CONCAT(LENGTH(rv), ':', rv);
  RETURN rv;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_DECODE_STRING;

DELIMITER //

CREATE FUNCTION __OBJ_DECODE_STRING(obj MEDIUMBLOB)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE pl MEDIUMBLOB DEFAULT NULL;
  DECLARE tp MEDIUMBLOB DEFAULT NULL;
  DECLARE rv MEDIUMBLOB DEFAULT NULL;
  SET pl = __OBJ_FIRST_ITEM_PAYLOAD(obj);
  IF pl IS NULL THEN
    RETURN NULL;
  END IF;
  SET tp = __OBJ_ITEM_PAYLOAD_TYPE(pl);
  IF tp IS NULL OR (tp <> 's' AND tp <> 'i' AND tp <> 'f') THEN
    RETURN NULL;
  END IF;
  SET rv = __OBJ_ITEM_PAYLOAD_RAW(pl);
  IF rv IS NULL THEN
    RETURN NULL;
  END IF;
  RETURN rv;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_SET_RAW;

DELIMITER //

CREATE FUNCTION __OBJ_SET_RAW(obj MEDIUMBLOB, tag TEXT, newval MEDIUMBLOB)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE rv MEDIUMBLOB DEFAULT NULL;
  DECLARE o MEDIUMBLOB DEFAULT NULL;
  DECLARE len BIGINT DEFAULT NULL;
  DECLARE ct MEDIUMBLOB DEFAULT NULL;
  DECLARE cv MEDIUMBLOB DEFAULT NULL;
  DECLARE ro MEDIUMBLOB DEFAULT '';
  DECLARE done BOOLEAN DEFAULT FALSE;
  SET len = __OBJ_FIRST_ITEM_LENGTH(obj);
  IF len IS NULL THEN
    RETURN  NULL;
  END IF;
  SET o = __OBJ_FIRST_ITEM_PAYLOAD(obj);
  IF o IS NULL THEN
    RETURN  NULL;
  END IF;
  IF __OBJ_ITEM_PAYLOAD_TYPE(o) <> 'o' THEN
   RETURN NULL;
  END IF;
  SET o = __OBJ_ITEM_PAYLOAD_RAW(o);
  IF o IS NULL THEN
    RETURN  NULL;
  END IF;
  IF newval IS NOT NULL THEN
    SET newval = __OBJ_FIRST_ITEM_PAYLOAD(newval);
    IF newval IS NULL THEN
      RETURN NULL;
    END IF;
  END IF;
  WHILE o <> '' DO
    SET len = __OBJ_FIRST_ITEM_LENGTH(o);
    IF len IS NULL THEN
      RETURN  NULL;
    END IF;
    SET ct = __OBJ_FIRST_ITEM_PAYLOAD(o);
    IF ct IS NULL THEN
      RETURN  NULL;
    END IF;
    SET ct = __OBJ_DECODE_STRING(CONCAT(LENGTH(ct), ':', ct));
    IF ct IS NULL THEN
      RETURN  NULL;
    END IF;
    SET o = SUBSTRING(o, len + 1);
    SET len = __OBJ_FIRST_ITEM_LENGTH(o);
    IF len IS NULL THEN
      RETURN  NULL;
    END IF;
    SET cv = __OBJ_FIRST_ITEM_PAYLOAD(o);
    IF cv IS NULL THEN
      RETURN  NULL;
    END IF;
    SET o = SUBSTRING(o, len + 1);
    IF ct = tag THEN
      IF newval IS NULL THEN
        SET cv = NULL;
      ELSE
        SET cv = newval;
      END IF;
      SET tag = ct;
      SET done = TRUE;
    END IF;
    IF cv IS NOT NULL THEN
      IF ro <> '' THEN
        SET ro = CONCAT(ro, ':');
      END IF;
      SET ro = CONCAT(ro, __OBJ_ENCODE_STRING(ct), ':', LENGTH(cv), ':', cv);
    END IF;
  END WHILE;
  IF NOT done AND newval IS NOT NULL THEN
    IF ro <> '' THEN
      SET ro = CONCAT(ro, ':');
    END IF;
    SET ro = CONCAT(ro, __OBJ_ENCODE_STRING(tag), ':', LENGTH(newval), ':', newval);
  END IF;
  SET rv = CONCAT('o', ':', ro);
  SET rv = CONCAT(LENGTH(rv), ':', rv);
  RETURN rv;
END; //

DELIMITER ;

DROP FUNCTION IF EXISTS __OBJ_GET_RAW;

DELIMITER //

CREATE FUNCTION __OBJ_GET_RAW(obj MEDIUMBLOB, tag TEXT)
RETURNS MEDIUMBLOB
DETERMINISTIC NO SQL
BEGIN
  DECLARE rv MEDIUMBLOB DEFAULT NULL;
  DECLARE o MEDIUMBLOB DEFAULT NULL;
  DECLARE len BIGINT DEFAULT NULL;
  DECLARE ct MEDIUMBLOB DEFAULT NULL;
  DECLARE cv MEDIUMBLOB DEFAULT NULL;
  SET len = __OBJ_FIRST_ITEM_LENGTH(obj);
  IF len IS NULL THEN
    RETURN  NULL;
  END IF;
  SET o = __OBJ_FIRST_ITEM_PAYLOAD(obj);
  IF o IS NULL THEN
    RETURN  NULL;
  END IF;
  IF __OBJ_ITEM_PAYLOAD_TYPE(o) <> 'o' THEN
   RETURN NULL;
  END IF;
  SET o = __OBJ_ITEM_PAYLOAD_RAW(o);
  IF o IS NULL THEN
    RETURN  NULL;
  END IF;
  WHILE o <> '' DO
    SET len = __OBJ_FIRST_ITEM_LENGTH(o);
    IF len IS NULL THEN
      RETURN  NULL;
    END IF;
    SET ct = __OBJ_FIRST_ITEM_PAYLOAD(o);
    IF ct IS NULL THEN
      RETURN  NULL;
    END IF;
    SET ct = __OBJ_DECODE_STRING(CONCAT(LENGTH(ct), ':', ct));
    IF ct IS NULL THEN
      RETURN  NULL;
    END IF;
    SET o = SUBSTRING(o, len + 1);
    SET len = __OBJ_FIRST_ITEM_LENGTH(o);
    IF len IS NULL THEN
      RETURN  NULL;
    END IF;
    SET cv = __OBJ_FIRST_ITEM_PAYLOAD(o);
    IF cv IS NULL THEN
      RETURN  NULL;
    END IF;
    SET o = SUBSTRING(o, len + 1);
    IF ct = tag THEN
      RETURN CONCAT(LENGTH(cv), ':', cv);
    END IF;
  END WHILE;
  RETURN NULL;
END; //

DELIMITER ;
